import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useListGithubUsers } from "../querys/useGitHubUsers.query";
import UserCard from "../components/UserCard";
import Searcher from "../components/Search";

export default function Home() {
  // Hook para listar todos los usuarios si no hay búsqueda activa
  const {
    data: usersData,
    isLoading: isLoadingList,
    isError: isErrorList,
  } = useListGithubUsers();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          {/* Componente de búsqueda */}
          <Searcher className={styles.searchContainer} />
        </div>

        {isLoadingList && <h1>Cargando datos...</h1>}

        {/* Mostrar error si lo hay */}
        {isErrorList && <h1>Error al obtener los usuarios</h1>}

        {/* Mostrar la lista de usuarios, completa o filtrada */}
        {!isLoadingList && !isErrorList && usersData && (
          <main className={styles.main}>
            {usersData.map((user) => (
              <UserCard key={user.id} user={user} />
            ))}
          </main>
        )}
      </div>
    </>
  );
}
